def _make_theme(
    *,
    name: str,
    primary: str,
    secondary: str,
    accent: str,
    bg: str,
    sidebar: str,
    card: str,
    button_hover: str,
    emoji: str,
    desc: str,
    greeting: str,
    welcome: str,
    focus_label: str,
    short_break_label: str,
    long_break_label: str,
    timer_title: str,
    study_title: str,
    celebration: str,
    new_achievement: str,
    level_prefix: str,
    streak_msg: str,
    xp_name: str,
    # ── valores com default (derivados) ──
    text: str = "#FFFFFF",
    text_sec: str | None = None,
    success: str = "#4CAF50",
    danger: str = "#F44336",
    warning: str = "#FFC107",
    button: str | None = None,
    entry_bg: str | None = None,
    entry_border: str | None = None,
    progress: str | None = None,
) -> dict:
    """Cria um tema derivando button/entry_bg/entry_border/progress quando omitidos."""
    return {
        "primary": primary,
        "secondary": secondary,
        "accent": accent,
        "bg": bg,
        "sidebar": sidebar,
        "card": card,
        "text": text,
        "text_sec": text_sec or "#B8B8CC",
        "success": success,
        "danger": danger,
        "warning": warning,
        "button": button or primary,
        "button_hover": button_hover,
        "entry_bg": entry_bg or card,
        "entry_border": entry_border or primary,
        "progress": progress or primary,
        "emoji": emoji,
        "desc": desc,
        "greeting": greeting,
        "welcome": welcome,
        "focus_label": focus_label,
        "short_break_label": short_break_label,
        "long_break_label": long_break_label,
        "timer_title": timer_title,
        "study_title": study_title,
        "celebration": celebration,
        "new_achievement": new_achievement,
        "level_prefix": level_prefix,
        "streak_msg": streak_msg,
        "xp_name": xp_name,
    }


THEMES = {
    "Naruto": _make_theme(
        name="Naruto",
        primary="#FF6B00", secondary="#1A1A2E", accent="#FFD700",
        bg="#0F0F1A", sidebar="#0A0A15", card="#16213E",
        button_hover="#FF8C00",
        emoji="🍥",
        desc="Tema inspirado no ninja mais imprevisível da Vila da Folha!",
        greeting="Dattebayo! {saudacao}, {nome}!",
        welcome="🍥 Bem-vindo à Vila da Folha, ninja!",
        focus_label="🍥 Treinamento Ninja",
        short_break_label="🍜 Hora do Rámen",
        long_break_label="🌀 Meditação do Sábio",
        timer_title="🍥 Timer Ninja",
        study_title="📜 Pergaminhos de Estudo",
        celebration="Você é incrível, dattebayo! Todas as metas concluídas!",
        new_achievement="🍥 JUTSU DESBLOQUEADO: {emoji} {title}",
        level_prefix="Rank Ninja",
        streak_msg="🔥 {dias} dias de treinamento seguidos!",
        xp_name="Chakra",
    ),
    "Dragon Ball": _make_theme(
        name="Dragon Ball",
        primary="#FF8C00", secondary="#1E3A5F", accent="#FFD700",
        bg="#0D1B2A", sidebar="#081425", card="#1B2838",
        text_sec="#A0C4E8", button_hover="#FFA033",
        emoji="🟠",
        desc="Poder de mais de 8000! Estude como um Saiyajin!",
        greeting="Kame-hame-ha! {saudacao}, {nome}!",
        welcome="🟠 Bem-vindo, guerreiro Saiyajin!",
        focus_label="🟠 Treino na Câmara de Gravidade",
        short_break_label="🫘 Hora da Senzu",
        long_break_label="☁️ Descanso no Templo de Kami",
        timer_title="🟠 Timer Saiyajin",
        study_title="📡 Rastreador de Poder",
        celebration="Seu poder de luta ultrapassou 8000! Metas destruídas!",
        new_achievement="🐉 PODER DESBLOQUEADO: {emoji} {title}",
        level_prefix="Poder Nv.",
        streak_msg="🔥 {dias} dias treinando sem parar!",
        xp_name="Ki",
    ),
    "Demon Slayer": _make_theme(
        name="Demon Slayer",
        primary="#00BFA5", secondary="#1A1A2E", accent="#FF6B9D",
        bg="#0F0F1A", sidebar="#0A0A15", card="#1A1A2E",
        text_sec="#A0E8D8", success="#00BFA5", danger="#FF6B9D",
        warning="#FFD700", button_hover="#00D4B8",
        emoji="🔥",
        desc="Concentração total! Respire e estude como um Caçador de Demônios!",
        greeting="Concentração total! {saudacao}, {nome}!",
        welcome="🔥 Bem-vindo ao Corpo de Caçadores de Demônios!",
        focus_label="🌊 Respiração da Água — Foco",
        short_break_label="🦋 Descanso da Borboleta",
        long_break_label="🌸 Recuperação no Monte Natagumo",
        timer_title="🔥 Timer Caçador",
        study_title="⚔️ Treinamento de Respiração",
        celebration="Respiração total dominada! Todas as metas cortadas!",
        new_achievement="⚔️ FORMA DESBLOQUEADA: {emoji} {title}",
        level_prefix="Rank Caçador",
        streak_msg="🔥 {dias} dias de respiração contínua!",
        xp_name="Respiração",
    ),
    "Attack on Titan": _make_theme(
        name="Attack on Titan",
        primary="#8B4513", secondary="#2C2C2C", accent="#C0392B",
        bg="#1A1A1A", sidebar="#121212", card="#2C2C2C",
        text="#E0E0E0", text_sec="#A0A0A0",
        success="#27AE60", danger="#C0392B", warning="#F39C12",
        button_hover="#A0522D",
        emoji="⚔️",
        desc="Dedique seu coração aos estudos! Shinzou wo Sasageyo!",
        greeting="Shinzou wo Sasageyo! {saudacao}, {nome}!",
        welcome="⚔️ Bem-vindo ao Corpo de Exploração!",
        focus_label="⚔️ Missão Além das Muralhas",
        short_break_label="🏰 Retorno à Muralha",
        long_break_label="🛡️ Descanso no Quartel General",
        timer_title="⚔️ Timer do Corpo de Exploração",
        study_title="📋 Plano de Batalha",
        celebration="Missão completa, soldado! Coração dedicado com sucesso!",
        new_achievement="🎖️ PATENTE CONQUISTADA: {emoji} {title}",
        level_prefix="Patente",
        streak_msg="⚔️ {dias} dias de dedicação total!",
        xp_name="Honra",
    ),
    "My Hero Academia": _make_theme(
        name="My Hero Academia",
        primary="#2ECC71", secondary="#1A237E", accent="#F1C40F",
        bg="#0D1340", sidebar="#080E30", card="#1A237E",
        text_sec="#A8D8A8", danger="#E74C3C",
        button_hover="#3AE680",
        emoji="💪",
        desc="Plus Ultra! Vá além dos seus limites nos estudos!",
        greeting="Plus Ultra! {saudacao}, {nome}!",
        welcome="💪 Bem-vindo à U.A. High School!",
        focus_label="💪 Treino de Individualidade",
        short_break_label="🎒 Intervalo na U.A.",
        long_break_label="🏥 Recovery Girl — Descanso Total",
        timer_title="💪 Timer Plus Ultra",
        study_title="📖 Aula na U.A. High",
        celebration="Plus Ultra! Você superou todos os limites hoje!",
        new_achievement="🦸 INDIVIDUALIDADE DESPERTA: {emoji} {title}",
        level_prefix="Herói Nv.",
        streak_msg="💪 {dias} dias sendo Plus Ultra!",
        xp_name="Hero Points",
    ),
    "One Piece": _make_theme(
        name="One Piece",
        primary="#E74C3C", secondary="#1A1A2E", accent="#F1C40F",
        bg="#0F0F1A", sidebar="#0A0A15", card="#1A1A2E",
        text_sec="#F0C0B0", danger="#E74C3C",
        button_hover="#FF6B5A",
        emoji="🏴‍☠️",
        desc="O Rei dos Estudantes será você! Aventura no saber!",
        greeting="Yohoho! {saudacao}, {nome}!",
        welcome="🏴‍☠️ Bem-vindo ao Thousand Sunny, nakama!",
        focus_label="⛵ Navegando pelo Conhecimento",
        short_break_label="🍖 Banquete do Luffy",
        long_break_label="🏝️ Descanso na Ilha",
        timer_title="🏴‍☠️ Timer Pirata",
        study_title="🗺️ Mapa do Tesouro do Saber",
        celebration="KAIZOKU OU NI ORE WA NARU! Todas as metas conquistadas!",
        new_achievement="💎 TESOURO ENCONTRADO: {emoji} {title}",
        level_prefix="Bounty Nv.",
        streak_msg="⛵ {dias} dias navegando sem parar!",
        xp_name="Berries",
    ),
    "Death Note": _make_theme(
        name="Death Note",
        primary="#9B59B6", secondary="#1A1A1A", accent="#C0392B",
        bg="#0D0D0D", sidebar="#080808", card="#1A1A1A",
        text="#E0E0E0", text_sec="#B8A0C8",
        success="#27AE60", danger="#C0392B", warning="#F39C12",
        button_hover="#B07CC6",
        emoji="📓",
        desc="Escreva seu nome no caderno... do sucesso nos estudos!",
        greeting="Keikaku doori... {saudacao}, {nome}.",
        welcome="📓 Bem-vindo. O caderno está em suas mãos.",
        focus_label="📓 Escrevendo no Death Note",
        short_break_label="🍎 Pausa com a Maçã do Ryuk",
        long_break_label="🖤 Meditação de L",
        timer_title="📓 Timer do Caderno",
        study_title="🔍 Investigação de L",
        celebration="Tudo conforme o planejado. Metas eliminadas com sucesso.",
        new_achievement="📓 ANOTAÇÃO REGISTRADA: {emoji} {title}",
        level_prefix="Intelecto Nv.",
        streak_msg="📓 {dias} dias de planejamento perfeito.",
        xp_name="QI",
    ),
    "Jujutsu Kaisen": _make_theme(
        name="Jujutsu Kaisen",
        primary="#3498DB", secondary="#1A1A2E", accent="#E74C3C",
        bg="#0A0A1A", sidebar="#060612", card="#141428",
        text_sec="#8AB4D8", danger="#E74C3C",
        button_hover="#5DADE2",
        emoji="👁️",
        desc="Domínio de estudo expandido! Energia amaldiçoada nos livros!",
        greeting="Ryouiki Tenkai! {saudacao}, {nome}!",
        welcome="👁️ Bem-vindo à Escola de Feiticeiros de Tokyo!",
        focus_label="👁️ Expansão de Domínio",
        short_break_label="🐼 Pausa com o Panda",
        long_break_label="⚡ Recarga de Energia Amaldiçoada",
        timer_title="👁️ Timer Amaldiçoado",
        study_title="📿 Grimório Amaldiçoado",
        celebration="Domínio expandido com sucesso! Metas exorcizadas!",
        new_achievement="👁️ TÉCNICA DESPERTA: {emoji} {title}",
        level_prefix="Feiticeiro Nv.",
        streak_msg="👁️ {dias} dias canalizando energia!",
        xp_name="Energia Amaldiçoada",
    ),
    "Stranger Things": _make_theme(
        name="Stranger Things",
        primary="#E74C3C", secondary="#1A1A2E", accent="#3498DB",
        bg="#0D0D1A", sidebar="#080812", card="#1A1A2E",
        text_sec="#D0A0A0", danger="#E74C3C",
        button_hover="#FF6B5A",
        emoji="💡",
        desc="O Mundo Invertido dos estudos! Luzes piscando = hora de estudar!",
        greeting="As luzes piscaram! {saudacao}, {nome}!",
        welcome="💡 Bem-vindo a Hawkins! Cuidado com o Mundo Invertido...",
        focus_label="💡 Investigação em Hawkins",
        short_break_label="🧇 Pausa para Waffles da Eleven",
        long_break_label="🏠 Descanso no Porão do Mike",
        timer_title="💡 Timer de Hawkins",
        study_title="📻 Comunicação do Mundo Invertido",
        celebration="Gate fechado! Todas as metas resolvidas, amigos!",
        new_achievement="💡 PODER DESBLOQUEADO: {emoji} {title}",
        level_prefix="Agente Nv.",
        streak_msg="💡 {dias} dias sobrevivendo em Hawkins!",
        xp_name="Poderes Psíquicos",
    ),
    "Breaking Bad": _make_theme(
        name="Breaking Bad",
        primary="#27AE60", secondary="#1A2E1A", accent="#F1C40F",
        bg="#0D1A0D", sidebar="#081208", card="#1A2E1A",
        text="#E0FFE0", text_sec="#A0C8A0",
        danger="#E74C3C",
        button_hover="#2ECC71",
        emoji="🧪",
        desc="Say my name... Estudante nota 10! Ciência pura nos estudos!",
        greeting="Say my name! {saudacao}, {nome}!",
        welcome="🧪 Bem-vindo ao Laboratório. A ciência do estudo começa!",
        focus_label="🧪 Cozinhando Conhecimento",
        short_break_label="☕ Café com o Hank",
        long_break_label="🏜️ Descanso no Deserto",
        timer_title="🧪 Timer do Heisenberg",
        study_title="⚗️ Laboratório de Estudos",
        celebration="99.1% de pureza! Metas sintetizadas com perfeição!",
        new_achievement="🧪 FÓRMULA DESCOBERTA: {emoji} {title}",
        level_prefix="Químico Nv.",
        streak_msg="🧪 {dias} dias no laboratório!",
        xp_name="Pureza",
    ),
}

CALM_W3_PALETTE = {
    "primary": "#04AA6D",
    "secondary": "#2B3A46",
    "accent": "#D9EEE1",
    "bg": "#1D2A35",
    "sidebar": "#18232E",
    "card": "#22303C",
    "text": "#E7E9EB",
    "text_sec": "#B7C4CD",
    "success": "#04AA6D",
    "danger": "#C97777",
    "warning": "#D4B56A",
    "button": "#059862",
    "button_hover": "#04AA6D",
    "entry_bg": "#263744",
    "entry_border": "#3C5364",
    "progress": "#04AA6D",
    "surface_alt": "#2B3E4C",
    "surface_soft": "#08FFFFFF",
    "shadow_dark": "#38091118",
    "shadow_light": "#0DFFFFFF",
}

THEME_COLOR_KEYS = [
    "primary",
    "secondary",
    "accent",
    "bg",
    "sidebar",
    "card",
    "text",
    "text_sec",
    "success",
    "danger",
    "warning",
    "button",
    "button_hover",
    "entry_bg",
    "entry_border",
    "progress",
    "surface_alt",
    "surface_soft",
    "shadow_dark",
    "shadow_light",
]

THEMES["W3 Calm"] = {
    **CALM_W3_PALETTE,
    "emoji": "🟢",
    "desc": "Tema suave inspirado no tom visual do W3Schools, com contraste confortável.",
    "greeting": "{saudacao}, {nome}!",
    "welcome": "Bem-vindo ao seu espaço de estudos.",
    "focus_label": "Sessão de foco",
    "short_break_label": "Pausa curta",
    "long_break_label": "Pausa longa",
    "timer_title": "Pomodoro",
    "study_title": "Estudar",
    "celebration": "Excelente progresso hoje. Continue nesse ritmo.",
    "new_achievement": "Nova conquista: {emoji} {title}",
    "level_prefix": "Nível",
    "streak_msg": "{dias} dias de constância",
    "xp_name": "XP",
}

for theme_name, theme in THEMES.items():
    if theme_name != "W3 Calm":
        for key in THEME_COLOR_KEYS:
            theme.setdefault(key, CALM_W3_PALETTE[key])

DEFAULT_THEME = "W3 Calm"


class ThemeManager:
    def __init__(self):
        self.current_theme = DEFAULT_THEME

    def get_theme(self, name=None):
        name = name or self.current_theme
        return THEMES.get(name, THEMES[DEFAULT_THEME])

    def set_theme(self, name):
        if name in THEMES:
            self.current_theme = name
