THEMES = {
    "Naruto": {
        "primary": "#FF6B00",
        "secondary": "#1A1A2E",
        "accent": "#FFD700",
        "bg": "#0F0F1A",
        "sidebar": "#0A0A15",
        "card": "#16213E",
        "text": "#FFFFFF",
        "text_sec": "#B8B8CC",
        "success": "#4CAF50",
        "danger": "#F44336",
        "warning": "#FFC107",
        "button": "#FF6B00",
        "button_hover": "#FF8C00",
        "entry_bg": "#16213E",
        "entry_border": "#FF6B00",
        "progress": "#FF6B00",
        "emoji": "🍥",
        "desc": "Tema inspirado no ninja mais imprevisível da Vila da Folha!",
    },
    "Dragon Ball": {
        "primary": "#FF8C00",
        "secondary": "#1E3A5F",
        "accent": "#FFD700",
        "bg": "#0D1B2A",
        "sidebar": "#081425",
        "card": "#1B2838",
        "text": "#FFFFFF",
        "text_sec": "#A0C4E8",
        "success": "#4CAF50",
        "danger": "#F44336",
        "warning": "#FFC107",
        "button": "#FF8C00",
        "button_hover": "#FFA033",
        "entry_bg": "#1B2838",
        "entry_border": "#FF8C00",
        "progress": "#FF8C00",
        "emoji": "🟠",
        "desc": "Poder de mais de 8000! Estude como um Saiyajin!",
    },
    "Demon Slayer": {
        "primary": "#00BFA5",
        "secondary": "#1A1A2E",
        "accent": "#FF6B9D",
        "bg": "#0F0F1A",
        "sidebar": "#0A0A15",
        "card": "#1A1A2E",
        "text": "#FFFFFF",
        "text_sec": "#A0E8D8",
        "success": "#00BFA5",
        "danger": "#FF6B9D",
        "warning": "#FFD700",
        "button": "#00BFA5",
        "button_hover": "#00D4B8",
        "entry_bg": "#1A1A2E",
        "entry_border": "#00BFA5",
        "progress": "#00BFA5",
        "emoji": "🔥",
        "desc": "Concentração total! Respire e estude como um Caçador de Demônios!",
    },
    "Attack on Titan": {
        "primary": "#8B4513",
        "secondary": "#2C2C2C",
        "accent": "#C0392B",
        "bg": "#1A1A1A",
        "sidebar": "#121212",
        "card": "#2C2C2C",
        "text": "#E0E0E0",
        "text_sec": "#A0A0A0",
        "success": "#27AE60",
        "danger": "#C0392B",
        "warning": "#F39C12",
        "button": "#8B4513",
        "button_hover": "#A0522D",
        "entry_bg": "#2C2C2C",
        "entry_border": "#8B4513",
        "progress": "#8B4513",
        "emoji": "⚔️",
        "desc": "Dedique seu coração aos estudos! Shinzou wo Sasageyo!",
    },
    "My Hero Academia": {
        "primary": "#2ECC71",
        "secondary": "#1A237E",
        "accent": "#F1C40F",
        "bg": "#0D1340",
        "sidebar": "#080E30",
        "card": "#1A237E",
        "text": "#FFFFFF",
        "text_sec": "#A8D8A8",
        "success": "#2ECC71",
        "danger": "#E74C3C",
        "warning": "#F1C40F",
        "button": "#2ECC71",
        "button_hover": "#3AE680",
        "entry_bg": "#1A237E",
        "entry_border": "#2ECC71",
        "progress": "#2ECC71",
        "emoji": "💪",
        "desc": "Plus Ultra! Vá além dos seus limites nos estudos!",
    },
    "One Piece": {
        "primary": "#E74C3C",
        "secondary": "#1A1A2E",
        "accent": "#F1C40F",
        "bg": "#0F0F1A",
        "sidebar": "#0A0A15",
        "card": "#1A1A2E",
        "text": "#FFFFFF",
        "text_sec": "#F0C0B0",
        "success": "#2ECC71",
        "danger": "#E74C3C",
        "warning": "#F1C40F",
        "button": "#E74C3C",
        "button_hover": "#FF6B5A",
        "entry_bg": "#1A1A2E",
        "entry_border": "#E74C3C",
        "progress": "#E74C3C",
        "emoji": "🏴‍☠️",
        "desc": "O Rei dos Estudantes será você! Aventura no saber!",
    },
    "Death Note": {
        "primary": "#9B59B6",
        "secondary": "#1A1A1A",
        "accent": "#C0392B",
        "bg": "#0D0D0D",
        "sidebar": "#080808",
        "card": "#1A1A1A",
        "text": "#E0E0E0",
        "text_sec": "#B8A0C8",
        "success": "#27AE60",
        "danger": "#C0392B",
        "warning": "#F39C12",
        "button": "#9B59B6",
        "button_hover": "#B07CC6",
        "entry_bg": "#1A1A1A",
        "entry_border": "#9B59B6",
        "progress": "#9B59B6",
        "emoji": "📓",
        "desc": "Escreva seu nome no caderno... do sucesso nos estudos!",
    },
    "Jujutsu Kaisen": {
        "primary": "#3498DB",
        "secondary": "#1A1A2E",
        "accent": "#E74C3C",
        "bg": "#0A0A1A",
        "sidebar": "#060612",
        "card": "#141428",
        "text": "#FFFFFF",
        "text_sec": "#8AB4D8",
        "success": "#2ECC71",
        "danger": "#E74C3C",
        "warning": "#F1C40F",
        "button": "#3498DB",
        "button_hover": "#5DADE2",
        "entry_bg": "#141428",
        "entry_border": "#3498DB",
        "progress": "#3498DB",
        "emoji": "👁️",
        "desc": "Domínio de estudo expandido! Energia amaldiçoada nos livros!",
    },
    "Stranger Things": {
        "primary": "#E74C3C",
        "secondary": "#1A1A2E",
        "accent": "#3498DB",
        "bg": "#0D0D1A",
        "sidebar": "#080812",
        "card": "#1A1A2E",
        "text": "#FFFFFF",
        "text_sec": "#D0A0A0",
        "success": "#2ECC71",
        "danger": "#E74C3C",
        "warning": "#F1C40F",
        "button": "#E74C3C",
        "button_hover": "#FF6B5A",
        "entry_bg": "#1A1A2E",
        "entry_border": "#E74C3C",
        "progress": "#E74C3C",
        "emoji": "💡",
        "desc": "O Mundo Invertido dos estudos! Luzes piscando = hora de estudar!",
    },
    "Breaking Bad": {
        "primary": "#27AE60",
        "secondary": "#1A2E1A",
        "accent": "#F1C40F",
        "bg": "#0D1A0D",
        "sidebar": "#081208",
        "card": "#1A2E1A",
        "text": "#E0FFE0",
        "text_sec": "#A0C8A0",
        "success": "#27AE60",
        "danger": "#E74C3C",
        "warning": "#F1C40F",
        "button": "#27AE60",
        "button_hover": "#2ECC71",
        "entry_bg": "#1A2E1A",
        "entry_border": "#27AE60",
        "progress": "#27AE60",
        "emoji": "🧪",
        "desc": "Say my name... Estudante nota 10! Ciência pura nos estudos!",
    },
}

DEFAULT_THEME = "Naruto"


class ThemeManager:
    def __init__(self):
        self.current_theme = DEFAULT_THEME

    def get_theme(self, name=None):
        name = name or self.current_theme
        return THEMES.get(name, THEMES[DEFAULT_THEME])

    def set_theme(self, name):
        if name in THEMES:
            self.current_theme = name

    def list_themes(self):
        return list(THEMES.keys())

    def get_color(self, key, name=None):
        theme = self.get_theme(name)
        return theme.get(key, "#FFFFFF")
